---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: splunk01
    image: splunk/splunk:7.2
    pre_build_image: true
    ports:
      - 8000:8000
    env-file:
      - splunk.env
    groups:
      - master
      - deployer
      - deployment_server
      - license-master
      - search_head_captain
  - name: splunk02
    image: splunk/splunk:7.2
    pre_build_image: true
    ports:
      - 8000:8000
    env-file:
      - splunk.env
    groups:
      - heavy_forwarder
  - name: splunk03
    image: splunk/splunk:7.2
    pre_build_image: true
    ports:
      - 8000:8000
    env-file:
      - splunk.env
    groups:
      - indexer
  - name: splunk04
    image: splunk/splunk:7.2
    pre_build_image: true
    ports:
      - 8000:8000
    env-file:
      - splunk.env
    groups:
      - search_head
  - name: splun05
    image: splunk/splunk:7.2
    pre_build_image: true
    ports:
      - 8000:8000
    env-file:
      - splunk.env
    groups:
      - universal_forwarder
provisioner:
  name: ansible
verifier:
  name: ansible
